server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/zippydb}
    username: ${SPRING_DATASOURCE_USERNAME:zippy}
    password: ${SPRING_DATASOURCE_PASSWORD:zippy}

couriers:
  fastship:
    base-url: http://mock-courier-service:8081
  quickexpress:
    base-url: http://mock-courier-service:8081
  reliable:
    base-url: http://mock-courier-service:8081
